### ISSUE TITLE
How to share my chat?

### ISSUE THREAD

**Issue by shiyuhang0** [vercel-labs/ai-chatbot#111]
I deploy myself but find share does not work with the following error
![image](https://github.com/vercel-labs/ai-chatbot/assets/52435083/ae8ef7cc-eae9-427a-8f0c-0ae7cba57aaf)
```
Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError: Failed to parse URL from /_next/static/media/Inter-Regular.970da903.woff","reason":{"errorType":"TypeError","errorMessage":"Failed to parse URL from /_next/static/media/Inter-Regular.970da903.woff","stack":["TypeError: Failed to parse URL from /_next/static/media/Inter-Regular.970da903.woff","    at new Request (node:internal/deps/undici/undici:7043:19)","    at r (/var/task/.next/server/chunks/264.js:825:65)","    at doOriginalFetch (/var/task/node_modules/.pnpm/next@13.4.7-canary.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/patch-fetch.js:273:24)","    at /var/task/node_modules/.pnpm/next@13.4.7-canary.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/patch-fetch.js:392:20","    at /var/task/node_modules/.pnpm/next@13.4.7-canary.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/trace/tracer.js:117:36","    at NoopContextManager.with (/var/task/node_modules/.pnpm/next@13.4.7-canary.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7057)","    at ContextAPI.with (/var/task/node_modules/.pnpm/next@13.4.7-canary.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:516)","    at NoopTracer.startActiveSpan (/var/task/node_modules/.pnpm/next@13.4.7-canary.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18086)","    at ProxyTracer.startActiveSpan (/var/task/node_modules/.pnpm/next@13.4.7-canary.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18847)","    at /var/task/node_modules/.pnpm/next@13.4.7-canary.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/trace/tracer.js:106:107"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: TypeError: Failed to parse URL from /_next/static/media/Inter-Regular.970da903.woff","    at process.<anonymous> (file:///var/runtime/index.mjs:1186:17)","    at process.emit (node:events:525:35)","    at emit (node:internal/process/promises:149:20)","    at processPromiseRejections (node:internal/process/promises:283:27)","    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)"]}
Unknown application error occurred
Runtime.Unknown
```

**Comment by shiyuhang0** [comment]
I delete the following code in share/page.tsx as a workaround
```
const interRegular = fetch(
  new URL('../../../assets/fonts/Inter-Regular.woff', import.meta.url)
).then(res => res.arrayBuffer())

const interBold = fetch(
  new URL('../../../assets/fonts/Inter-Bold.woff', import.meta.url)
).then(res => res.arrayBuffer())
```

**Comment by Saran33** [comment]
Does anyone know why the demo on [chat.vercel.ai](https://chat.vercel.ai) has a `Share` button in the [ChatPanel](https://github.com/vercel-labs/ai-chatbot/blob/5744f56ff6d02517746530de0ef9d04e150834ac/components/chat-panel.tsx) but it's not included in any branch or commit of this repo? I just added it in myself locally to match the demo version.

**Comment by Saran33** [comment]
In case anyone else is wondering, I split the sharing confirmation dialog logic from the `sidebar-actions.tsx` into its own `ShareDialog` component. I made a `ChatShareButton` component to wrap it and included it in the chat panel. I set its visibility based on a new optional `chat` prop passed to the `ChatPanel` (with the chat prop passed to the `Chat` component in `app/chat/[id]/page.tsx`). Added a new  optional `chatId` prop to the `PromptForm`. In the `PromptForm`, after the `onSubmit` call, I included `router.push(chatId ? `/chat/${chatId}` : '/chat');`.  

I presume something like this is being done in the demo app, but no idea why it's not in the repo. There's still the issue of the chat history in the `SidebarList` not being updated when a new chat is created. It is only updated when the page is refreshed. Personally I am using a separate Python backend, so will probably use a good ol' fashioned useEffect here to trigger an API call or something for the time being. Not ideal though. The server actions pattern is awesome. Really helps  with keeping tokens away from the client.

**Comment by ericmanyc** [comment]
Hi @Saran33, can you share your code for this logic?

**Comment by leerob** [comment]
We ended up removing this open graph image file as it's a nice to have 🙏
