### ISSUE TITLE
 unhandledRejection: Error: Response error: No response body

### ISSUE THREAD

**Issue by codergautam** [vercel-labs/ai-chatbot#146]
I'm running the app with the code specified in the npm package documentation, but getting the weird error 
```
error unhandledRejection: Error: Response error: No response body
    at Object.start (webpack-internal:///(rsc)/./node_modules/.pnpm/ai@2.1.25_react@18.2.0_solid-js@1.7.11_svelte@4.2.0_vue@3.3.4/node_modules/ai/dist/index.mjs:137:38)
    at g (eval at requireWithFakeGlobalScope (/Users/codergautam/Documents/projects/prompt-finder/node_modules/.pnpm/next@13.4.12_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/edge-runtime/index.js:1:970334), <anonymous>:102:35)
    at Object.eval [as start] (eval at requireWithFakeGlobalScope (/Users/codergautam/Documents/projects/prompt-finder/node_modules/.pnpm/next@13.4.12_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/edge-runtime/index.js:1:970334), <anonymous>:1708:29)
    at It.a2 (eval at requireWithFakeGlobalScope (/Users/codergautam/Documents/projects/prompt-finder/node_modules/.pnpm/next@13.4.12_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/edge-runtime/index.js:1:970334), <anonymous>:1689:39)
    at eval (eval at requireWithFakeGlobalScope (/Users/codergautam/Documents/projects/prompt-finder/node_modules/.pnpm/next@13.4.12_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/edge-runtime/index.js:1:970334), <anonymous>:1691:333)
    at It (eval at requireWithFakeGlobalScope (/Users/codergautam/Documents/projects/prompt-finder/node_modules/.pnpm/next@13.4.12_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/edge-runtime/index.js:1:970334), <anonymous>:1692:4)
    at new ReadableStream (eval at requireWithFakeGlobalScope (/Users/codergautam/Documents/projects/prompt-finder/node_modules/.pnpm/next@13.4.12_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/edge-runtime/index.js:1:970334), <anonymous>:1770:7)
    at AIStream (webpack-internal:///(rsc)/./node_modules/.pnpm/ai@2.1.25_react@18.2.0_solid-js@1.7.11_svelte@4.2.0_vue@3.3.4/node_modules/ai/dist/index.mjs:135:20)
    at OpenAIStream (webpack-internal:///(rsc)/./node_modules/.pnpm/ai@2.1.25_react@18.2.0_solid-js@1.7.11_svelte@4.2.0_vue@3.3.4/node_modules/ai/dist/index.mjs:177:20)
    at POST (webpack-internal:///(rsc)/./app/api/chat/route.js:23:68) {
  digest: undefined
}
```

Endpoint code:

```
import OpenAI from 'openai';
import { OpenAIStream, StreamingTextResponse } from 'ai';

console.log("API Key", process.env.OPENAI_API_KEY);
const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

export const runtime = 'edge';

export async function POST(req) {
  const { messages } = await req.json();
  console.log("Messages", messages);
  const response = await openai.chat.completions.create({
    model: 'gpt-4',
    stream: true,
    messages,
  });
  const stream = OpenAIStream(response);
  return new StreamingTextResponse(stream);
}
```

It works perfect when I replace 

```
  const stream = OpenAIStream(response);
  return new StreamingTextResponse(stream);
```
with
```
  for await (const message of response) {
    console.log("Message", message);
    return message;
  }
```

(Im getting chunks logged to console)

I already made sure that API key is defined, message format is proper, etc. Not sure if this is a bug with package itself, but this very simple use case should def work.. right?

**Comment by codergautam** [comment]
Edit: Its resolved now. For some reason `pnpm` installed an old version of `ai` (2.1.25) updating manually to `2.2.11` fixed the issue. Hope this helps someone!
