### ISSUE TITLE
TypeError [ERR_INVALID_URL]: Invalid URL

### ISSUE THREAD

**Issue by sytpb** [vercel-labs/ai-chatbot#153]
- error TypeError [ERR_INVALID_URL]: Invalid URL
    at __webpack_require__ (D:\work\chatgpt\yantaosong\ai-chatbot\.next\server\webpack-runtime.js:33:42)
    at eval (./components/login-button.tsx:9:73)
    at (sc_client)/./components/login-button.tsx (D:\work\chatgpt\yantaosong\ai-chatbot\.next\server\app\sign-in\page.js:706:1)
    at __webpack_require__ (D:\work\chatgpt\yantaosong\ai-chatbot\.next\server\webpack-runtime.js:33:42)

I want to  run it on local, and I have set the .env following the items  in .env.example .   

I don't why show me invaild URL , which URL ? 

![image](https://github.com/vercel-labs/ai-chatbot/assets/12178686/1d74a3e4-b8b1-4a34-ad0c-729752c8b09c)

is this configure right ? 
![image](https://github.com/vercel-labs/ai-chatbot/assets/12178686/3c2fc965-bd1f-4ea2-b1bb-02be19f7489d)

**Comment by sytpb** [comment]
The callback URL for github should be:

Local: http://localhost:3000/api/auth/callback/github
Prod: https://example.com/api/auth/callback/github

#28 
https://github.com/vercel-labs/ai-chatbot/issues/28#issuecomment-1598975610
