### ISSUE TITLE
- error TypeError [ERR_INVALID_URL]: Invalid URL

### ISSUE THREAD

**Issue by sytpb** [vercel-labs/ai-chatbot#156]
deploy on locally , and run ok , but something the log showed as following , 

- error TypeError [ERR_INVALID_URL]: Invalid URL
    at __webpack_require__ (D:\work\chatgpt\yantaosong\ai-chatbot\.next\server\edge-runtime-webpack.js:37:33)
    at fn (D:\work\chatgpt\yantaosong\ai-chatbot\.next\server\edge-runtime-webpack.js:310:21)
    at eval (./components/user-menu.tsx:7:73)
    at (sc_client)/./components/user-menu.tsx (D:\work\chatgpt\yantaosong\ai-chatbot\.next\server\app\page.js:645:1)
    at __webpack_require__ (D:\work\chatgpt\yantaosong\ai-chatbot\.next\server\edge-runtime-webpack.js:37:33)
    at fn (D:\work\chatgpt\yantaosong\ai-chatbot\.next\server\edge-runtime-webpack.js:310:21)

**Comment by bielrv** [comment]
same here

**Comment by lamroger** [comment]
Try setting NEXTAUTH_URL 

https://github.com/nextauthjs/next-auth/discussions/4220#discussioncomment-3188228

**Comment by leerob** [comment]
^ Thank you @lamroger!
