### ISSUE TITLE
Try to implement Prisma into this repo and always get error "unable to be run in the browser"

### ISSUE THREAD

**Issue by steveoOn** [vercel-labs/ai-chatbot#86]
I try to implement Prisma into this repo and always get the error "unable to be run in the browser"

Even import Prisma Client in app/Layout or other Serverside components.
```
- error Error: PrismaClient is unable to be run in the browser.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
    at eval (./lib/prisma.ts:10:52)
    at (sc_server)/./lib/prisma.ts (/Users/username/Documents/react-projects/Next-PJ/try-chatbot/.next/server/app/page.js:3270:1)
    at __webpack_require__ (/Users/username/Documents/react-projects/Next-PJ/try-chatbot/.next/server/edge-runtime-webpack.js:37:33)
    at fn (/Users/username/Documents/react-projects/Next-PJ/try-chatbot/.next/server/edge-runtime-webpack.js:310:21)
    at eval (./components/header.tsx:18:70)
    at (sc_server)/./components/header.tsx (/Users/username/Documents/react-projects/Next-PJ/try-chatbot/.next/server/app/page.js:2921:1)
    at __webpack_require__ (/Users/username/Documents/react-projects/Next-PJ/try-chatbot/.next/server/edge-runtime-webpack.js:37:33)
    at fn (/Users/username/Documents/react-projects/Next-PJ/try-chatbot/.next/server/edge-runtime-webpack.js:310:21)
    at eval (./app/layout.tsx:13:76)
```
prisma.ts was like:
```typescript
import { PrismaClient } from '@prisma/client'

declare global {
  var prisma: PrismaClient | undefined
}

// Check if we are on the server
if (typeof window === 'undefined') {
  const prisma = global.prisma || new PrismaClient()

  if (process.env.NODE_ENV === 'development') global.prisma = prisma
}

export default global.prisma
```
New to Next.js and have no idea how to fix it. please help~

**Comment by balazsorban44** [comment]
Hi, the error message is slightly confusing, but what happens is that you are trying to use Prisma in an Edge runtime, which Prisma does not support by default.

You have two options:

- Make Prisma edge compatible: https://www.prisma.io/blog/database-access-on-the-edge-8F0t1s1BqOJE
- Paths where you plan to use Prisma should not use the edge runtime

**Comment by steveoOn** [comment]
> Hi, the error message is slightly confusing, but what happens is that you are trying to use Prisma in the Edge runtime, which Prisma currently does not support by default.
> 
> You have two options:
> 
> * Make Prisma edge compatible: https://www.prisma.io/blog/database-access-on-the-edge-8F0t1s1BqOJE
> * Paths where you plan to use Prisma should not use the edge runtime

Hi, @balazsorban44, Thanks for your guidance. After running some tests, I've confirmed that the issue was caused by the edge runtime. The article you shared about how to use Prisma in edge runtime was super helpful, thank you so much!😄

**Comment by balazsorban44** [comment]
Glad that I could help! Can we close the issue then? 🙏

**Comment by miketikh** [comment]
Hi, running into a similar error. I'm continuously getting: 
`- error Error: PrismaClient is unable to be run under the Vercel Edge Runtime.`

Everywhere in the repo where it said `runtime = 'edge'` has been changed to `runtime = 'nodejs'`, as far as I can tell it shouldn't be using edge runtime. Is there anywhere else I might have to edit?
