### ISSUE TITLE
Gettings 429 response when using the default setup with Open AI

### ISSUE THREAD

**Issue by naz** [vercel-labs/ai-chatbot#92]
After deploying ai-chatbot and signing into the app, the prompting doesn't work. 

In the Vercel platform logs show:
```
Error: Failed to convert the response to stream. Received status code: 429.
    at (node_modules/.pnpm/ai@2.1.6_react@18.2.0_svelte@3.59.2_vue@3.3.4/node_modules/ai/dist/index.mjs:112:10)
    at (node_modules/.pnpm/ai@2.1.6_react@18.2.0_svelte@3.59.2_vue@3.3.4/node_modules/ai/dist/index.mjs:140:9)
    at (app/api/chat/route.ts:38:17)
    at (node_modules/.pnpm/next@13.4.7-canary.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:210:36)
```
This makes me think there's an issue interacting with Open AI that causes a Rate limit error response?

**Comment by naz** [comment]
This is most likely related to a billing requirements with Open AI reported here too - https://github.com/vercel-labs/ai/issues/144#issuecomment-1596158004.

**Comment by naz** [comment]
Confirmed. After providing a credit card to OpenAI and regenerating the API key the app is working.
